.TH pattest 8 "2008-01-08" 
.SH NAME 
pattest \(em Tests a Pattern for a Zaptel Clear Channel Test
.SH SYNOPSIS 
.B pattest 
.I zap-device

.SH DESCRIPTION 
.B pattest
Recieves test data from a Zaptel channel and checks if it matches the 
test pattern. The channel should be of CLEAR signalling (e.g: B channel 
of a PRI line). patgen(8) is used to generate the data at the other side.  

.B pattest
Must be able to read from the channel. Hence this cannot be used for a
channel used by Asterisk.

The pattern is a simple series of values from 0 to 255. Hence it takes
at most one sample to get in sync with the other side. If there is no
output, all is well. Output is an error message.

.SH OPTIONS
.I zap-device
.RS
A Zaptel device file.
.RE

.SH EXAMPLE
  pattest /dev/zap/5

.SH BUGS
Will not work with channels whose number > 249 as they don't have device
files. For a simple workaround, see ztdiag.c .

Gives way too many errors when does not get any input.

.SH SEE ALSO 
patgen(8), ztcfg(8), asterisk(8). 

.SH AUTHOR 

This manual page was written by Tzafrir Cohen <tzafrir.cohen@xorcom.com> 
Permission is granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
