obj-m += wctdm24xxp.o

FIRM_DIR	:= ../../firmware

EXTRA_CFLAGS := -I$(src)/.. -Wno-undef

ifeq ($(HOTPLUG_FIRMWARE),yes)
  EXTRA_CFLAGS+=-DHOTPLUG_FIRMWARE
endif

wctdm24xxp-objs := base.o GpakCust.o GpakApi.o voicebus.o

ifneq ($(HOTPLUG_FIRMWARE),yes)
wctdm24xxp-objs += $(FIRM_DIR)/zaptel-fw-vpmadt032.o
endif

$(obj)/$(FIRM_DIR)/zaptel-fw-vpmadt032.o: $(obj)/base.o
	$(MAKE) -C $(obj)/$(FIRM_DIR) zaptel-fw-vpmadt032.o

$(obj)/base.o: $(src)/GpakCust.h $(src)/wctdm24xxp.h
$(obj)/base.o: $(src)/../zaptel.h

$(obj)/GpakCust.o: $(src)/GpakCust.h

$(obj)/GpakApi.o: $(src)/GpakApi.h
