obj-m += wcte12xp.o

FIRM_DIR	:= ../../firmware

EXTRA_CFLAGS := -I$(src)/.. -Wno-undef

ifeq ($(HOTPLUG_FIRMWARE),yes)
  EXTRA_CFLAGS+=-DHOTPLUG_FIRMWARE
endif

wcte12xp-objs := base.o vpmadt032.o GpakApi.o voicebus.o

ifneq ($(HOTPLUG_FIRMWARE),yes)
wcte12xp-objs += $(FIRM_DIR)/zaptel-fw-vpmadt032.o
endif

$(obj)/$(FIRM_DIR)/zaptel-fw-vpmadt032.o: $(obj)/base.o
	$(MAKE) -C $(obj)/$(FIRM_DIR) zaptel-fw-vpmadt032.o

$(obj)/base.o: $(src)/vpmadt032.h $(src)/wcte12xp.h
$(obj)/base.o: $(src)/../zaptel.h

$(obj)/vpmadt032.o: $(src)/vpmadt032.h

$(obj)/GpakApi.o: $(src)/GpakApi.h
