#!/usr/bin/env bash
set -o errexit

# N4IRS 07/26/2017

#####################################################
#                                                   #
#Stop unneeded services and listenere               #
#                                                   #
#####################################################

# Stop:
systemctl stop dhcpcd.service
systemctl stop avahi-daemon
systemctl stop ntp.service

# Disable:
systemctl disable dhcpcd.service
systemctl disable avahi-daemon
systemctl disable ntp.service

# Enable:
systemctl enable systemd-networkd.service
systemctl enable systemd-resolved.service
systemctl enable systemd-networkd-wait-online.service

/srv/scripts/mk_eth0.network.sh

# Start:
systemctl start systemd-networkd.service
systemctl start systemd-resolved.service

ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf

ntpd -gq > /dev/null 2>&1 &

systemctl set-default multi-user.target
ln -fs /lib/systemd/system/getty@.service /etc/systemd/system/getty.target.wants/getty@tty1.service

