
name: make_and_publish_pkgs
run-name: Package ${{ github.event.repository.name }}(${{ github.ref_name }}) for ${{ inputs.os }}/${{ inputs.arch }}, Publish to ${{ inputs.deployment-environment }}
on: 
  workflow_dispatch:
    inputs:
      arch:
        type: choice
        options: 
        - amd64
        - arm64
        - armhf
        - riscv64
      os:
        type: choice
        options:
          - buster
          - bullseye
          - bookworm
          - trixie
          - sid
      deployment-environment:
        type: choice
        options:
        - development
        - testing
        - production
      commit-versioning:
        type: choice
        options:
          - default
          - yes
          - no
jobs:
  make-packages:
    uses: AllStarLink/asl_workflows/.github/workflows/ephemeral_ec2_run-this.yml@develop
    with:
      run-this: ./docker/dockerbuild.sh -a ${{ inputs.arch  }} -o ${{ inputs.os }} ${{ (inputs.commit-versioning == 'yes' || (inputs.commit-versioning == 'default' && inputs.deployment-environment == 'development')) && '-r' || null }}
      arch: ${{ inputs.arch == 'armhf' && 'arm64' || inputs.arch == 'amd64' && 'x86_64' || inputs.arch == 'riscv64' && 'x86_64' || inputs.arch }}
      artifact-path: 'build/*'
    secrets: inherit
  publish-packages:
    uses: AllStarLink/asl_workflows/.github/workflows/publish_artifacts_to_aptly.yml@develop
    with:
      repo-name: asl_builds-${{inputs.os}}${{ inputs.deployment-environment == 'production' && '' || inputs.deployment-environment == 'testing' && '-testing' || inputs.deployment-environment == 'development' && '-devel' || null }}
    secrets: inherit
    needs: make-packages
