
name: make_x86_64_pkgs
on: workflow_dispatch
jobs:
  call-workflow-passing-data:
    uses: AllStarLink/asl_workflows/.github/workflows/ephemeral_ec2_run-this.yml@develop
    with:
      run-this: docker run hello-world
      arch: x86_64
      artifact-path: '*.deb'
    secrets: inherit
